### ISSUE TITLE
Failed to download sources: port 443: Connection refused

### ISSUE THREAD

**Issue by bam80** [flatpak/flatpak-builder#250] opened 2019-01-07 12:47 UTC
https://github.com/Pixelnarium/flatpak/blob/master/com.dosbox.DOSBox/com.dosbox.DOSBox.json
```
$ flatpak-builder --force-clean --ccache build-dir com.dosbox.DOSBox.json 
Downloading sources
Downloading http://http.debian.net/debian/pool/main/s/smpeg/smpeg_0.4.5+cvs20030824.orig.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   342  100   342    0     0    971      0 --:--:-- --:--:-- --:--:--   974
100  332k  100  332k    0     0   434k      0 --:--:-- --:--:-- --:--:-- 2909k
Downloading https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz
Failed to download sources: module SDL_sound: Failed to connect to icculus.org port 443: Connection refused
```
https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz downloadable outside without problems

**Comment by AsciiWolf** [comment] 2019-01-07 23:08
Hmm, weird. Maybe we could use [some mirror](https://www.google.com/search?q=%22SDL_sound-1.0.3.tar.gz%22).

**Comment by Pixelnarium** [comment] 2019-01-08 09:59
Works for me on my system. Maybe some DNS cache issue? The server was moved lately. See [here](https://twitter.com/icculus/status/1076669756781023232)

**Comment by alexlarsson** [comment] 2019-01-10 11:32
It looks like there is a http to https redirect. Maybe that is the cause? Does it work if you set the https uri directly?

**Comment by alexlarsson** [comment] 2019-01-10 11:32
Oh, no i misread. Those were different uris...

**Comment by alexlarsson** [comment] 2019-01-10 11:33
Does downloading it with curl work? That is what flatpak-builder uses.

**Comment by bam80** [comment] 2019-01-10 13:31
Hmm, for some reason it doesn't work neither with curl nor wget.
But it DOES work in browser! 
```
$ curl https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz
curl: (7) Failed to connect to icculus.org port 443: Connection refused
$ wget https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz
--2019-01-10 16:24:55--  https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz
Resolving icculus.org... 159.203.69.7, 2604:a880:800:a1::71f:3001
Connecting to icculus.org|159.203.69.7|:443... failed: Connection refused.
Connecting to icculus.org|2604:a880:800:a1::71f:3001|:443... failed: Network is unreachable.

**Comment by alexlarsson** [comment] 2019-01-10 15:58
`curl https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz --output file` works here. I wonder what is different for you. Goes to the same ip too.

I wonder if its an ipv6 thing? Can you try `curl --ipv4`

**Comment by bam80** [comment] 2019-01-10 16:17
> Can you try `curl --ipv4`

The same. I even don't have ipv6.

**Comment by alexlarsson** [comment] 2019-01-10 16:19
Honestly, I have no idea why this doesn't work. But given that it works for others, and also affects curl/wget i'm going to close this as "not a flatpak-builder" bug.

Obviously that doesn't really help you. Sorry about being useless there...

**Closed by alexlarsson** 2019-01-10 16:19 UTC

**Comment by alexlarsson** [comment] 2019-01-10 16:21
You can try 
```
strace -o log -f -y curl https://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz --output file
```
And look at `log` to see where its getting the connection refused from

**Comment by alexlarsson** [comment] 2019-01-10 16:48
I suspect a network error of some sort. Maybe a firewall. But yeah, how the hell does it work for the browser???
