### ISSUE TITLE
[Bug]: Failed to find installed SDK when building a package

### ISSUE THREAD

**Issue by HiPhish** [flatpak/flatpak-builder#549] opened 2023-04-28 17:04 UTC
### flatpak-builder version

1.3.1

### Flatpak version

1.15.4

### How to reproduce

1. Install Flatpak builder from Flathub
2. Follow instructions from [build tutorial](https://docs.flatpak.org/en/latest/first-build.html)
3. Make it to step four

### Expected Behavior

The flatpak should build correctly

### Actual Behavior

The builder cannot find the installed SDK. Running it in verbose mode yields this output:

```
$ flatpak run org.flatpak.Builder --verbose --repo=repo --force-clean build-dir org.flatpak.Hello.yml
FB: Running: git config --get user.email
FB: Running: git config --get user.name
FB: Running 'flatpak info --arch=x86_64 --show-commit org.freedesktop.Sdk 22.08' on host
Failed to init: Unable to find sdk org.freedesktop.Sdk version 22.08
```

However, if I run that last command manually I do get a commit hash:

``` 
$ flatpak info --arch=x86_64 --show-commit org.freedesktop.Sdk 22.08
2652112cf6f02f590602d3379a36a0e59d801a120f8ba4bb43170e75e3ab73da
```

So the SDK is installed, but the builder cannot find it. If I instruct the builder to automatically install dependencies I get a dbus error:

```
$ flatpak run org.flatpak.Builder --verbose --install-deps-from=flathub --repo=repo --force-clean build-dir org.flatpak.Hello.yml
FB: Running: git config --get user.email
FB: Running: git config --get user.name
Dependency Sdk: org.freedesktop.Sdk 22.08
FB: Running 'flatpak --system info org.freedesktop.Sdk/x86_64/22.08 --show-commit' on host
Installing org.freedesktop.Sdk/x86_64/22.08 from flathub
FB: Using Flatpak version 1.14.1
FB: Running 'flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk/x86_64/22.08' on host
Error installing deps: running `flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk/x86_64/22.08`: Cannot autolaunch D-Bus without X11 $DISPLAY
```

Yet the `$DISPLAY` variable is set to `:0`

### Additional Information

I am running [Void Linux](https://voidlinux.org/).

**Comment by TingPing** [comment] 2023-04-28 18:14
Duplicate of #383

**Closed by TingPing** 2023-04-28 18:14 UTC
Labels: bug
