### ISSUE TITLE
Provide an option to build with empty or no runtime/sdk

### ISSUE THREAD

**Issue by lawl** [flatpak/flatpak-builder#357] opened 2020-07-07 02:01 UTC
## Linux distribution and version

n/a

## Flatpak-builder version

1.0.10

## Flatpak version

1.6.3

## Description of the problem

I have a statically linked binary that I'd like to package as a flatpak. However the flatpak docs say one needs to depend on a runtime. For statically linked self-contained binary, this is not necessary.  
People in IRC have told me that it is currently not possible for a flatpak to have no runtime.

I would also prefer not having a dependency on something that is entirely unnecessary.

Even though such a flatpak wouldn't use its main selling point, I believe this also provides other benefits, over just letting them download the binary:

* Updates
* It's in their package manager, like everything else
* Sandboxing

I would really like to have an option to specify no runtime. Snap package builds already offer this in the form of a `base: bare` directive.

## Steps to reproduce

Try to build a flatpack without a runtime and/or SDK.

**Comment by mwleeds** [comment] 2020-07-07 02:25
Duplicate of https://github.com/flatpak/flatpak/issues/329

Maybe try making a runtime with nothing or almost nothing in it?

**Closed by mwleeds** 2020-07-07 02:25 UTC
