### ISSUE TITLE
Path resolution problem if multiple source manifests used

### ISSUE THREAD

**Issue by gcampax** [flatpak/flatpak-builder#282] opened 2019-05-01 04:04 UTC
## Linux distribution and version
Ubuntu 18.04+PPA

## Flatpak-builder version
1.0.6-flatpak1~bionic

## Description of the problem

If you have two modules that make use of the "include source manifest file", the second one will be looked up in the wrong directory.
What I mean is something like this:
```
{ ...
  "modules": [
     {
        "name": "one",
        "sources": [ "./subdir/one.json" ]
     },
     {
        "name": "two",
        "sources": [ "./subdir/two.json" ]
     }
   ]
}
```

The second json file will be looked at `subdir/subdir/two.json` (ie, the directory is appended twice), and that fails.
Instead, I expect that both are looked up relative to the location of the json file that includes them, as they normally are.

Note that this only happens for manifest snippets that list sources, not for snippets that are whole modules. And it is only a problem if the json file is in a subdirectory.

**Comment by gasinvein** [comment] 2019-08-02 18:15
Same issue here, reproducible both locally on Fedora 30 and with the Flathub's buildbot.

**Comment by gasinvein** [comment] 2020-10-28 11:44
Seems like the source subdir from previous module gets prepended to the next one. If there is many such modules, paths can get very long and tricky to workaround with symlinks.

**Comment by syco** [comment] 2021-06-28 16:10
Any news on this? Looks like all references go around in a loop and no one posted a solution.

Thanks

**Comment by gasinvein** [comment] 2021-06-28 17:02
@syco There is no solution on the app side, this could only be fixed in flatpak-builder.

**Closed** 2021-07-24 19:12 UTC
