### ISSUE TITLE
[Feature Request] Support for Mercurial sources in the manifest

### ISSUE THREAD

**Issue by dos1** [flatpak/flatpak-builder#225] opened 2018-10-31 23:52 UTC
I've just had to resort to unofficial github mirror in order to build a dependency which is developed using Mercurial. It would be nice to have it supported in flatpak-builder as a build source, like git is supported now.

**Comment by QuLogic** [comment] 2024-12-24 05:28
This is a duplicate of #235 (which I don't understand how it's older yet has a higher issue number.)

**Closed** 2024-12-25 20:19 UTC
